[package]
name = "wml2"
version = "0.0.5"
authors = ["mith-mmk <47620686+mith-mmk@users.noreply.github.com>"]
edition = "2021"
license = "MIT"

[lib]
crate-type = ["rlib"] 

[dependencies]

[dependencies.bin-rs]
git = "https://github.com/mith-mmk/bin-rs"
version = "0.0.1"
features = ["stream"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = 3
