[package]
name = "wml2"
version = "0.0.10-alpha1"
repository = "https://github.com/mith-mmk/wml2-on-rust"
homepage = "https://mith-mmk.github.io/"
authors = ["mith-mmk <47620686+mith-mmk@users.noreply.github.com>"]
description = "WML2 - Web graphic Multi format Library"
edition = "2021"
license = "MIT"
tags = ["image","jpeg","gif","png","bmp","exif"]

[lib]
crate-type = ["rlib"] 

[features]
#bmp = []
#gif = []
#jpeg = []
#png = []
#tiff = []
#all = []
multithread = []

[dependencies]
bin-rs = {version = "0.0.7",features = ["stream","util"]}
#bin-rs = {path = "../bin-rs",features = ["stream","util"]}
miniz_oxide =  {version = "0.5.1"}

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = 3
