[package]
name = "wml2"
version = "0.0.12-alpha1"
repository = "https://github.com/mith-mmk/wml2-on-rust"
homepage = "https://mith-mmk.github.io/"
authors = ["mith-mmk <47620686+mith-mmk@users.noreply.github.com>"]
description = "WML2 - Web graphic Multi format Library"
edition = "2021"
rust-version = "1.60"
license = "MIT"
keywords = ["image","jpeg","gif","png","bmp","exif","tiff"]

[lib]
crate-type = ["rlib"] 

[features]
#bmp = []
#gif = []
#jpeg = []
#use LL&M for IDCT
idct_llm = []   
#use Slower for IDCT
idct_slowerm = [] 
#default use AAN for IDCT
#png = []
#tiff = []
#all = []
# use multithread
multithread = []

[dependencies]
bin-rs = {version = "0.0.7",features = ["stream","util"]}
miniz_oxide = {version = "0.5.1"}

[profile.release]
opt-level = 3
