name: build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      - name: cache cargo
        uses: Swatinem/rust-cache@v2

      - name: build examples
        run: cargo build --release --examples

      # Windows: *.exe のみ
      - name: archive (windows)
        if: runner.os == 'Windows'
        run: |
          cd target/release/examples
          powershell Compress-Archive -Path *.exe -DestinationPath ../examples-${{ matrix.os }}.zip

      # Unix系: 拡張子なしのみ
      - name: archive (linux/mac)
        if: runner.os != 'Windows'
        run: |
          cd target/release/examples
          files=$(find . -type f ! -name "*.*")
          zip -r ../examples-${{ matrix.os }}.zip $files

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: examples-${{ matrix.os }}
          path: target/release/examples-${{ matrix.os }}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/examples-${{ matrix.os }}.zip