name: build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --release --examples

      - name: archive (windows)
        if: runner.os == 'Windows'
        run: |
          cd target/release/examples
          powershell Compress-Archive -Path *.exe -DestinationPath ../examples-${{ matrix.os }}.zip

      - name: archive (unix)
        if: runner.os != 'Windows'
        run: |
          cd target/release/examples
          files=$(find . -type f ! -name "*.*" ! -regex '.*-[0-9a-f]\{16\}$')
          zip -r ../examples-${{ matrix.os }}.zip $files

      - uses: actions/upload-artifact@v4
        with:
          name: examples-${{ matrix.os }}
          path: target/release/examples-${{ matrix.os }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*.zip
          overwrite_files: true