name: viewer

on:
  push:
    tags:
      - "wml*"

jobs:
  build:
    strategy:
      matrix:
#        os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      - name: cache cargo
        uses: Swatinem/rust-cache@v2

      - name: build wml2viewer
        run: cargo build --release -p wml2viewer

      - name: prepare dist
        run: |
          mkdir dist

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/release/wml2viewer.exe dist/wml2viewer.exe
            cd dist && zip wml2viewer-windows.zip wml2viewer.exe
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            cp target/release/wml2viewer dist/wml2viewer
            cd dist && zip wml2viewer-macos.zip wml2viewer
          else
            cp target/release/wml2viewer dist/wml2viewer
            cd dist && zip wml2viewer-linux.zip wml2viewer
          fi
        shell: bash

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*